from .MasteringEffects import NODE_CLASS_MAPPINGS as ME_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ME_DISPLAY
from .CompressorNode import NODE_CLASS_MAPPINGS as COMP_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as COMP_DISPLAY
from .LimiterNode import NODE_CLASS_MAPPINGS as LIM_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LIM_DISPLAY
from .MasteringSuiteNode import NODE_CLASS_MAPPINGS as MS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MS_DISPLAY
from .AudioPostProcessor import NODE_CLASS_MAPPINGS as APP_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as APP_DISPLAY
from .ArrangementEnforcer import NODE_CLASS_MAPPINGS as AE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as AE_DISPLAY

NODE_CLASS_MAPPINGS = {
    **ME_MAPPINGS,
    **COMP_MAPPINGS,
    **LIM_MAPPINGS,
    **MS_MAPPINGS,
    **APP_MAPPINGS,
    **AE_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **ME_DISPLAY,
    **COMP_DISPLAY,
    **LIM_DISPLAY,
    **MS_DISPLAY,
    **APP_DISPLAY,
    **AE_DISPLAY
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']